### PR TITLE
Pascal's Triangle

### PR DESCRIPTION
**Pull request by ARYAMANSHIVAMJHA**

### CODE REVIEW

**Comment by ARYAMANSHIVAMJHA** [comment]
The pull request is not being reflected in the hacktoberfest count. Could
you please clarify

**Comment by akshitagupta15june** [comment]
it will start from 1st october.

**Comment by ARYAMANSHIVAMJHA** [comment]
so will these count ??

**Comment by akshitagupta15june** [comment]
no these will not be counted only the pr on or after 1st october.
but they can be as a practice

**Pull request closed without merging**
