### PR TITLE
Create triangle.cpp

### PR DESCRIPTION
**Pull request by jayadevvasudevan**
completed first half

### CODE REVIEW

**Comment by jayadevvasudevan** [comment]
first half of issue

**Comment by akshitagupta15june** [comment]
Try to make it full!!

**Comment by jayadevvasudevan** [comment]
okay

**Comment by jayadevvasudevan** [comment]
should i put this in daily code??

**Comment by akshitagupta15june** [comment]
code is added a few seconds before!! issue closed
save it for partice purpose , work on more issues.

**Pull request closed without merging**
